"""Configuration settings for the autonomous perception system."""
from .settings import (
    ALLOWED_EXTENSIONS,
    DETECTION_PROMPTS,
    MAX_FRAME_DIM,
    MODEL_CONFIDENCE,
    MODEL_IOU,
    MODEL_PATH,
    OBSTACLE_CLASSES,
    RISK_CRITICAL,
    RISK_WARNING,
    SERVER_DEBUG,
    SERVER_HOST,
    SERVER_PORT,
    SERVER_THREADED,
    UPLOAD_FOLDER,
)

__all__ = [
    "ALLOWED_EXTENSIONS",
    "DETECTION_PROMPTS",
    "MAX_FRAME_DIM",
    "MODEL_CONFIDENCE",
    "MODEL_IOU",
    "MODEL_PATH",
    "OBSTACLE_CLASSES",
    "RISK_CRITICAL",
    "RISK_WARNING",
    "SERVER_DEBUG",
    "SERVER_HOST",
    "SERVER_PORT",
    "SERVER_THREADED",
    "UPLOAD_FOLDER",
]
